# Generated by Django 3.2.8 on 2022-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipregistration1',
            name='reg_date',
            field=models.DateField(default=''),
        ),
    ]
