# Generated by Django 3.2.8 on 2022-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='college',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='attach_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
