# Generated by Django 3.2.8 on 2022-01-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20220122_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipregistration1',
            name='end_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipregistration1',
            name='start_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
