# Generated by Django 4.0.1 on 2022-01-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_auto_20220128_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
