# Generated by Django 4.0.1 on 2022-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_delete_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='qrcode1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img/%y')),
                ('qr_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='qrcode2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrid', models.IntegerField()),
            ],
        ),
    ]
