# Generated by Django 4.0.1 on 2022-01-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_qrcode1_qrcode2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode2',
            name='qrid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
