# Generated by Django 4.0.1 on 2022-01-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_qrcode2_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode2',
            name='img2',
        ),
    ]
