# Generated by Django 4.0.1 on 2022-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_remove_qrcode2_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode1',
            name='img',
            field=models.ImageField(default='', max_length=1000, upload_to='img/%y'),
        ),
    ]
